apiVersion: v1
kind: Service
metadata:
  name: mydb-service
  labels:
    app: mydb-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    app: nginx-pod
