apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    env: myservice
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    env: nginx-pod
