apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    env: demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    run: nginx-pod # ✅ This now matches your pod's label
