apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react-service
spec:
  selector:
    app: react
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30008
